name: first-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello Shiva Ram" 
          echo "How are you?"
          echo "You can Rock"
        
